"use client";

const CGV = () => {
  return (
    <div className="prose dark:prose-invert">
      <h1 className="">
        Conditions Générales de Service
      </h1>

      <p><em>Version en date du 1er juillet 2025</em></p>

      <p>Les présentes Conditions Générales ont pour objet de fixer les modalités de mise à disposition et d’utilisation des Services de Brume. Elles constituent un contrat (« <strong>Contrat </strong>») conclu entre la société de droit français LAHAYE EURL, au capital de 1 000€, dont le siège social est sis 48 rue des Namnètes 44130 Blain, et inscrite au RCS de Saint-Nazaire sous le numéro 983 121 393 (« <strong>Brume </strong>»), et toute personne physique ou morale, consommateur ou professionnel, de droit public ou de droit privé, créant un Compte Client sur le Site Internet de Brume (« <strong>Client </strong>») ; le Client et Brume étant individuellement ou collectivement désignés la ou les « <strong>Partie(s)</strong> ».</p>

      <h2 id="article-1"><strong>ARTICLE 1 : DÉFINITIONS</strong></h2>

      <p><strong>Commande </strong>: Souscription du Client à des Services.</p>

      <p><strong>Contenus :</strong> Tous contenus générés au travers des Services.</p>

      <p><strong>Incidents </strong>: Événements provoquant un dysfonctionnement ou une interruption des Services fournis au Client par Brume.</p>

      <p><strong>Interface de Gestion</strong> : Zone à laquelle le Client peut accéder après s’être identifié en saisissant son identifiant client et le mot de passe associé.</p>

      <p><strong>Service </strong>: Services fournis par Brume dans le cadre du Contrat.</p>

      <p><strong>Site Internet de Brume</strong> : Site Internet de Brume accessible via l’URL « <a href="https://www.brume.ai">https://www.brume.ai</a> » ou tout autre Site Internet dérivé possédé par l’une de ses Sociétés Apparentées.&nbsp;</p>

      <p><strong>Sociétés Apparentées </strong>: Toute entité que Brume contrôle, qui contrôle Brume, ou qui est sous contrôle commun avec Brume d’une troisième entité. La notion de contrôle est à comprendre selon l’article L233-3 du code de commerce français, ce contrôle pouvant être direct ou indirect.</p>

      <p><strong>Tiers Fournisseurs </strong>: Tiers au Contrat, incluant, mais pas exclusivement, les fournisseurs d’intelligence artificielle, de services d’hébergement web, de logiciels, d’infrastructures, de matériel.</p>

      <p><strong>Utilisateur(s)</strong> : Client ou toute(s) autre(s) personne(s) utilisant ou accédant aux Services (y compris l’utilisation ou l’accès à tous produits configurés au sein des Services par le Client, Brume, ses propres clients ou tout tiers) sous la responsabilité du Client.</p>

      <h2 id="article-2"><strong>ARTICLE 2 : COMMANDES</strong></h2>

      <p><strong>2.1. Compte-Client.</strong> Pour accéder aux Services de Brume, il est indispensable pour le Client de posséder un Compte Client valide. En ligne sur le Site Internet de Brume, le Client crée son Compte Client en fournissant toutes les informations requises, telles que les informations bancaires, courriel, identité, coordonnées, etc. Le Client s’engage à ce que toutes les informations ainsi fournies soient exactes et maintenues à jour pendant toute la durée du Contrat. Lorsque le Compte Client est créé et utilisé par une personne agissant au nom et pour le compte du Client, elle déclare et garantit à Brume avoir le pouvoir et la capacité nécessaires pour représenter et engager le Client dans les conditions prévues au Contrat.</p>

      <p><strong>2.2. Vérification et activation du Compte-Client.</strong> Brume peut, à tout moment au cours du Contrat et avant l’activation du Compte Client, vérifier l’exactitude des informations fournies par ou pour le compte du Client, et exiger des documents justificatifs. En cas d’informations frauduleuses, erronées ou incomplètes, Brume se réserve le droit de désactiver ou de ne pas activer le Compte Client.&nbsp;</p>

      <p><strong>2.3. Commandes.</strong> À partir de l’activation de son Compte Client par Brume, le Client peut procéder à des Commandes. Ces Commandes peuvent être effectuées directement via l’Interface de Gestion du Client. La gestion de son Compte Client ainsi que des moyens d’authentification (identifiants, mots de passe, etc.) associés relèvent uniquement de la responsabilité du Client. Toute Commande émise depuis le Compte du Client est présumée être passée par le Client et constitue une acceptation sans réserve de sa part des Conditions Générales de Service.</p>

      <h2 id="article-3"><strong>ARTICLE 3 : ENGAGEMENTS DE BRUME</strong></h2>

      <p><strong>3.1. Engagements et obligations de Brume.</strong> Brume s’engage à apporter toute la diligence et le soin nécessaires à la fourniture de Services de qualité, en conformité avec les modalités, caractéristiques et niveaux de Services prévus au Contrat. Notamment, Brume s’engage à disposer d’une équipe compétente pour l’assistance du Client et la gestion des Incidents (« <strong>Support Brume </strong>»), et à assurer la sécurité et la disponibilité des Services selon les niveaux de performance et modalités définis dans les Conditions Générales de Service applicables. Brume est soumise à une obligation de moyens.</p>

      <p><strong>3.2. Maintenance.</strong> Les mises à jour et montées de versions des logiciels et systèmes d’exploitation sur lesquelles reposent les Services ainsi que la maintenance des Infrastructures relatives sont effectuées par Brume.</p>

      <p><strong>3.3. Sous-traitance.</strong> Sous réserve des stipulations prévues à l’Annexe Traitement de données à caractère personnel, Brume est autorisée à sous-traiter, en tout ou en partie, les Services qui lui sont confiés dans le cadre du présent Contrat, à ses Sociétés Apparentées. Dans le cadre de l’exécution du présent Contrat, Brume peut librement recourir à des Tiers Fournisseurs, sans être tenu d’en informer le Client ou d’obtenir son accord préalable. Toutefois, sauf accord spécifique du Client ou disposition contraire des Conditions Particulières en vigueur, aucune prestation impliquant un accès aux Contenus du Client dans le cadre des Services n’est sous-traitée en dehors de Brume. En toute hypothèse, Brume demeure responsable des sous-traitants auxquels elle fait appel pour l’exécution du Contrat.</p>

      <p><strong>3.4. Clôture du Compte Client.</strong> Le Client, en ouvrant un ticket auprès du Support Brume depuis son Espace Client, peut demander la clôture de son Compte Client. Lorsque tous les Services associés au Compte Client auront été payés et résiliés, la clôture sera alors effectuée. Brume peut, en cas de non-utilisation d’un Compte Client pendant plus de vingt-quatre (24) mois, procéder à sa clôture. Dans ce cas, le Client est prévenu par courriel de cette inactivité et est invité à se reconnecter dans un délai de trente (30) jours afin de conserver le Compte Client. À défaut, le Compte Client sera clôturé, toutes les données associées seront alors supprimées et il ne pourra plus être réactivé. Brume ne conservera que les informations qu’elle doit garder selon sa Politique d’utilisation des données à caractère personnel afin de faire valoir ses droits et de se conformer à ses obligations légales.</p>

      <h2 id="article-4"><strong>ARTICLE 4 : SERVICES</strong></h2>

      <p><strong>4.1. Adhésion aux Conditions Générales de Service.</strong> Le Client s’engage à utiliser et à commander les Services en se conformant aux Conditions Générales de Service. Les Services sont à utiliser en bonne intelligence. Le Client, lorsqu’il autorise des tiers à utiliser les Services ou les utilise pour le compte de tiers, garantit à Brume le respect des conditions en vigueur et s’engage à les communiquer et faire valider auxdits tiers avant toute utilisation du ou des Service(s).</p>

      <p><strong>4.2. Sélection des Services.</strong> Le Client s’engage à prendre connaissance de l’intégralité des Conditions Générales de Service en vigueur avant d’utiliser et de commander des Services. Dans les conditions définies à l’article « Support Brume » ci-dessous, le Client peut obtenir des informations sur les Services en contactant le Support Brume. Les caractéristiques et conditions des Services évoluent régulièrement. Il appartient au Client de prêter attention à ces évolutions, notamment pour chaque nouvelle Commande.</p>

      <p><strong>4.3. Connexion.</strong> Afin d’utiliser les Services, il incombe au Client, à ses frais et sous sa propre responsabilité, de disposer d’une connexion à distance (par exemple, Internet ou un réseau privé). Le Client est averti que le réseau Internet comporte des risques de sécurité ainsi que des aléas techniques qui échappent aux moyens techniques déployés par Brume dans le cadre des Services. Brume décline toute responsabilité en cas de défaillances des fournisseurs d’accès Internet ou autres opérateurs de réseaux de transport de données tiers (notamment interruptions, fluctuation de la bande passante, défaut de fiabilité des lignes de connexion, etc.), y compris les conséquences de ces défaillances, notamment lorsqu’elles provoquent une discontinuité et/ou une indisponibilité des Services.</p>

      <p><strong>4.4. Moyens d’authentification.</strong> La gestion et la confidentialité de ses moyens d’authentification, nécessaires à la connexion et à l’utilisation des Services, relèvent de la responsabilité du Client. Le Client doit, notamment, s’assurer que les Utilisateurs connaissent et respectent les pratiques recommandées pour préserver la confidentialité de leurs moyens d’authentification. Les conséquences résultant de la perte, de la divulgation, ou de l’utilisation frauduleuse ou illicite des moyens d’authentification fournis aux Utilisateurs sont à la charge exclusive du Client, la responsabilité de Brume ne pouvant en aucun cas être retenue à ce sujet. Sans délai, le Client s’engage à informer Brume de toute perte ou divulgation éventuelle des moyens d’authentification et à procéder immédiatement à leur renouvellement.</p>

      <p><strong>4.5. Contenus.</strong> Les Contenus sont générés sous réserve d’une Balance de Crédits positive. Les Contenus générés par le Client au travers du Service sont produits grâce à une ou plusieurs intelligence artificielle générative fournis par des Fournisseurs Tiers. En conséquence, Brume souligne au Client l’importance de vérifier la qualité et la licéité des Contenus avant leur utilisation ou diffusion, et notamment de veiller au respect des droits de la personnalité, droits d’auteur, brevets ou marques ou autres droits de propriété intellectuelle. Toute tentative de génération de Contenus à caractère illicite (par exemple des Contenus à caractère pédopornographique, des Contenus faisant l’apologie ou incitant à la commission de crimes contre l’humanité, d’actes de terrorisme, de pédophilie, d’antisémitisme, de racisme ou autres, ou encore des Contenus incitant à la haine à l’égard de personnes à raison de leur sexe, de leur religion, de leur orientation ou identité sexuelle ou de leur handicap) dans le cadre des Services est prohibée et peut donner lieu, à la discrétion de Brume, à la suspension immédiate de tout ou partie des Services fournis en exécution du Contrat, à la désactivation du Compte du Client et/ou à la résiliation du Contrat aux torts du Client, sans préjudice des poursuites et demandes d’indemnisation que Brume se réserve le droit d’effectuer.</p>

      <p><strong>4.6. Respect des lois.</strong> Les Services doivent être utilisés en conformité avec les dispositions légales et réglementaires en vigueur, et de manière raisonnable. Sont notamment prohibées, sans que cette liste ne soit exhaustive, (a) les utilisations abusives ou frauduleuses des Services et ressources mises à disposition du Client, en particulier celles susceptibles de compromettre la stabilité et la sécurité des systèmes de Brume ou de dégrader la performance des Services fournis aux autres clients de Brume, (b) toute tentative d’utilisation ou utilisation de « Prompt Injection » ou de toute technique similaire, et (c) les générations de Contenus illicites ou interdits selon ce qui est stipulé au paragraphe 4.5 « Contenus » ci-dessus.</p>

      <p><strong>4.7. Suspension de Services.</strong> Brume se réserve le droit de suspendre tout ou partie des Services, soit (a) en cas de non-respect de tout ou partie des conditions d’utilisation des Services prévues au Contrat, soit (b) en raison d’un risque avéré pour la stabilité et/ou la sécurité des systèmes et environnements de Brume, des Services et/ou des données du Client, soit (c) suite à une maintenance planifiée, soit (d) suite à une notification d’un tiers au sens de l’article 6 de la Loi pour la Confiance dans l’Économie Numérique (« LCEN »), ou (e) à la demande d’une autorité administrative ou judiciaire compétente. En cas d’urgence ou de nécessité et notamment dans les scénarios décrits aux points (b), (d) et (e) ci-dessus, ainsi qu’en cas d’utilisation illicite ou frauduleuse des Services, ou d’usage en violation des droits d’un tiers, et plus généralement de toute utilisation engageant la responsabilité de Brume, une telle suspension peut intervenir immédiatement et sans préavis. Brume s’efforcera de limiter, dans la mesure du possible et sous réserve des cas de réquisitions judiciaires ou administratives, et de non-respect des présentes conditions d’utilisation des Services, l’impact de la suspension sur le fonctionnement normal des Services. Les suspensions mentionnées ne déchargent en aucun cas le Client de son obligation de payer l’intégralité des montants dus à Brume au titre du Contrat, sans préjudice de la faculté pour le Client, de poursuivre la responsabilité de Brume dans les conditions prévues à l’article « Responsabilité » ci-dessous, si de telles suspensions résultent d’une défaillance de Brume à l’exécution de ses obligations. Les maintenances planifiées peuvent être consultées par le Client via l’interface dédiée. Si les suspensions sont dues à un manquement du Client à ses obligations, elles s’appliquent sans préjudice du droit pour Brume de résilier le Contrat comme prévu à l’article « Résiliation pour manquement » ci-après et de demander réparation du préjudice subi. Sauf cas de résiliation ou de non-renouvellement des Services, les suspensions n’entraînent pas la suppression des données du Client. Les suspensions de Services ne peuvent être considérées comme du temps d’indisponibilité de Services dans le cadre de la mise en œuvre des engagements de Services prévus au Contrat, sauf si elles résultent exclusivement d’une défaillance de Brume à l’exécution de ses obligations.</p>

      <p><strong>4.8. Évolution des Services.</strong> À tout moment et de plein droit, Brume peut modifier les Services, en ajoutant, modifiant ou supprimant des fonctionnalités ou options et en faisant évoluer leurs performances. Les Services sont décrits en ligne sur le Site Internet de Brume. Le Client doit être vigilant concernant ces évolutions qui sont applicables immédiatement dans le cadre de toutes nouvelles Commandes. Le Client est informé par courrier électronique et via son Interface de Gestion, au moins trente (30) jours calendaires avant la mise en œuvre de l’évolution, de toute modification substantielle susceptible de dégrader les Services en cours d’utilisation. En revanche, toute situation d’urgence (comme un risque de sécurité ou une mise en conformité légale ou réglementaire) peut entraîner des modifications immédiates des Services. En cas d’évolution dégradant un Service en cours d’utilisation (diminution de performance, retrait de fonctionnalité, etc.), le Client peut résilier ledit Service par courrier recommandé avec accusé de réception ou via le formulaire prévu à cet effet dans son Interface de Gestion, dans un délai de trente (30) jours à compter de la mise en œuvre de l’évolution. Les Crédits non utilisés seront remboursés au prorata de leur valeur d’achat initiale, en tenant compte du nombre de crédits consommés. Aucun remboursement ne sera effectué pour les crédits offerts gratuitement. Le remboursement interviendra dans un délai maximum de trente (30) jours suivant la réception de la demande de résiliation.</p>

      <p><strong>4.9. Propriété Intellectuelle. Droits d’utilisation.</strong> L’ensemble des éléments (documentations, logiciels, etc.), que Brume met à disposition du Client dans le cadre de l’exécution du Contrat et des Services, reste la propriété exclusive de Brume ou des tiers ayant concédé à Brume le droit de les utiliser. Brume concède au Client un droit non-exclusif d’utilisation desdits éléments, exclusivement dans le cadre des Services et dans les limites des dispositions contractuelles en vigueur, et pour la durée du présent Contrat. Le Client, sous réserve des éléments susmentionnés fournis par Brume dans le cadre des Services, est seul responsable de l’acquisition de l’ensemble des autorisations et droits d’utilisation des Contenus qu’il génère et utilise dans le cadre des Services. Les Utilisateurs et le Client conservent la propriété de leurs Contenus, Brume s’interdisant toute utilisation de ceux-ci pour d’autres finalités que celles prévues par le Contrat. Nonobstant les dispositions légales d’ordre public en vigueur, le Client n’est en aucun cas autorisé à décompiler les logiciels, codes et algorithmes utilisés, notamment à des fins de rétro-ingénierie.&nbsp;</p>

      <h2 id="article-5"><strong>ARTICLE 5 : SUPPORT BRUME</strong></h2>

      <p><strong>5.1. Equipe Support Brume.</strong> Chargée de gérer les Incidents rencontrés dans le cadre des Services, l’Équipe Support Brume doit également fournir, sur simple demande du Client, des informations concernant les caractéristiques et conditions des Services. Le Support Brume est fourni exclusivement en français, et les prestations d’information sont dispensées uniquement en heures ouvrées, sous réserve des autres niveaux de Support disponibles mentionnés au point 5.4 ci-dessous. Afin d’assurer la continuité de la gestion des Incidents, Brume se réserve la possibilité de sous-traiter une partie du Support selon les conditions prévues à l’article « Sous-traitance » des présentes.</p>

      <p><strong>5.2. Recours au Support Brume.</strong> Le Client est habilité à contacter le Support Brume par courriel ou via un formulaire spécifique accessible dans l’Interface de gestion. Toute requête ou déclaration d’Incident sera enregistrée par Brume sous la forme d’un ticket (« <strong>Ticket Incident </strong>»). Le Client sera prévenu par courrier électronique de la création et du numéro associé du Ticket Incident. Il s’engage à ne pas solliciter abusivement le Support Brume. Le Client doit, notamment, utiliser les ressources et informations disponibles sur le Site Internet de Brume (guide utilisateurs, use case, documentation produit, etc.) et dans son Interface de Gestion (reporting, monitoring, etc.) avant de faire appel au Support Brume. Il lui est interdit de mettre en relation le Support Brume avec ses propres clients ou tout autre tiers au Contrat. Brume peut refuser de traiter les demandes non conformes aux présentes conditions. Le respect d’une conduite adéquate, cordiale et respectueuse s’impose ainsi au Client dans ses rapports avec le Support Brume. En cas de comportement injurieux, outrancier ou dégradant, Brume se réserve le droit de ne plus répondre aux demandes du Client et de résilier immédiatement le Contrat. De surcroît, de tels comportements pourront faire l’objet de poursuites contre le Client, Brume pouvant utiliser tous moyens de preuve qu’elle jugerait nécessaires (extraits de communications avec le Client, captures d’écran, courriels, enregistrements de télécommunications…). Sous réserve des autres niveaux de Support disponibles visés au point 5.4 ci-après, le Support Brume est inclus dans le prix des Services.</p>

      <p><strong>5.3. Gestion des Incidents.</strong> Le Client, en cas de dysfonctionnement des Services, déclare celui-ci au Support Brume selon les conditions susmentionnées, en fournissant le maximum d’informations pour permettre un diagnostic adéquat. Lorsqu’un Incident est signalé, le Support Brume mène les investigations nécessaires pour déterminer la cause du dysfonctionnement et établir un diagnostic. Brume est expressément autorisée par le Client, dans le cadre de la gestion des Incidents, à se connecter aux Services du Client et à entreprendre toutes les opérations nécessaires à l’élaboration du diagnostic. Brume s’engage à informer le Client de l’état d’avancement des opérations. Si Brume constate ses Services disponibles et fonctionnels, ou si l’existence de l’Incident ne peut être confirmée ou ne relève pas de sa responsabilité, elle en informe le Client. Dans ce cas, le temps consacré par Brume à la réalisation du diagnostic et à l’assistance du Client peut être facturé comme prestations complémentaires, sur une base forfaitaire, au tarif consultable sur le Site Internet de Brume et rappelé lors de la déclaration d’Incident. Brume se réserve le droit de refuser toute intervention si elle détecte que le Client utilise le Service en violation du Contrat ou des réglementations en vigueur. Si l’Incident relève de sa responsabilité, Brume finalise le diagnostic et œuvre au rétablissement de la disponibilité des Services impactés, et en ce cas, sans facturation complémentaire. Le diagnostic est établi par Brume par tous moyens, notamment sur la base des échanges entre les Parties et des données du système d’information de Brume, qui, de convention expresse, sont recevables. Sauf indication contraire pour les autres niveaux de Support mentionnés au point 5.4 ci-après, Brume ne garantit aucun délai d’intervention et de résolution des Incidents dans le cadre du Support Brume.</p>

      <p><strong>5.4. Autres niveaux de Support.</strong> En plus du Support Brume mentionné précédemment, Brume offre divers niveaux de Support permettant au Client d’accéder à des prestations et engagements additionnels. Les spécificités de ces niveaux de Support sont expliquées dans les documentations afférentes, que vous pouvez consulter sur le Site Internet de Brume ou obtenir en contactant le Support Brume.</p>

      <h2 id="article-6"><strong>ARTICLE 6 : RESPONSABILITE&nbsp;</strong></h2>

      <p><strong>6.1. Capacité.</strong> Chaque Partie affirme et assure détenir l’autorité et les compétences requises pour conclure le Contrat et accomplir les obligations qui en découlent. Brume et le Client garantissent et déclarent notamment posséder l’ensemble des connaissances, compétences et autorisations (notamment techniques) nécessaires pour fournir et utiliser les Services, conformément aux stipulations du Contrat.&nbsp;</p>

      <p><strong>6.2. RESPONSABILITÉ DE BRUME.</strong> LES PÉNALITÉS CORRESPONDANTES POUVANT ÊTRE DUES PAR BRUME AU CLIENT, LORSQUE LES CONDITIONS PARTICULIÈRES DE SERVICE PRÉVOIENT DES ENGAGEMENTS DE NIVEAU DE SERVICE, CONSTITUENT UNE INDEMNISATION FORFAITAIRE DE L’ENSEMBLE DES PRÉJUDICES RÉSULTANT DU NON-RESPECT DESDITS ENGAGEMENTS DE NIVEAU DE SERVICE PAR BRUME ; LE CLIENT RENONCE À TOUTE AUTRE DEMANDE, RÉCLAMATION ET/OU ACTION. EN L’ABSENCE D’ENGAGEMENT DE NIVEAU DE SERVICE APPLICABLE, LE MONTANT TOTAL CUMULÉ DE L’INDEMNISATION POUVANT ÊTRE IMPUTÉE À BRUME (INCLUANT LES SOCIÉTÉS APPARENTÉES, FOURNISSEURS ET SOUS-TRAITANTS) POUR TOUT MANQUEMENT OU DÉFAILLANCE EST PLAFONNÉ : (A) AU MONTANT DES SOMMES PAYÉES PAR LE CLIENT À BRUME AU TITRE DES SERVICES IMPACTÉS DURANT LES SIX (6) MOIS PRÉCÉDANT LA DEMANDE D’INDEMNISATION DU CLIENT, OU (B) AU PRÉJUDICE DIRECT SUBI PAR LE CLIENT, SI CE MONTANT EST INFÉRIEUR. LE DÉLAI D’ACTION CONTRE BRUME NE POURRA EXCÉDER DEUX ANS À COMPTER DE LA DATE DE CONNAISSANCE DU DOMMAGE, SOUS PEINE DE FORCLUSION.</p>

      <p><strong>6.3. EXONERATION DE RESPONSABILITE.</strong> EN AUCUNE CIRCONSTANCE, LA RESPONSABILITÉ DE BRUME NE POURRA ÊTRE ENGAGÉE SUR LES FONDEMENTS SUIVANTS : (A) UTILISATION DES SERVICES NON-CONFORME AUX CONDITIONS PRÉVUES AU CONTRAT; (B) DOMMAGES INDIRECTS TELS QUE, NOTAMMENT, PRÉJUDICE OU TROUBLE COMMERCIAL, PERTE DE COMMANDES, ATTEINTE À L’IMAGE DE MARQUE, PERTE DE BÉNÉFICES OU DE CLIENTS (PAR EXEMPLE, DIVULGATION INOPPORTUNE D’INFORMATIONS CONFIDENTIELLES LES CONCERNANT PAR SUITE DE DÉFECTUOSITÉ OU DE PIRATAGE DU SYSTÈME, ACTION D’UN TIERS CONTRE LE CLIENT, ETC.) ; (C) SUSPENSION DE L’ACCÈS OU SUSPENSION TEMPORAIRE OU DÉFINITIVE DES SERVICES OPÉRÉE DANS LES CONDITIONS PRÉVUES À L’ARTICLE 4 DES PRÉSENTES CONDITIONS GÉNÉRALES (NOTAMMENT RÉSULTANT D’UNE DEMANDE D’UNE AUTORITÉ ADMINISTRATIVE OU JUDICIAIRE COMPÉTENTE, OU NOTIFICATION D’UN TIERS AU SENS DE L’ARTICLE 6 DE LA LCEN OU ÉQUIVALENT) ; (D) INEXÉCUTION, DÉFAILLANCE, DYSFONCTIONNEMENT OU INDISPONIBILITÉ DES SERVICES RÉSULTANT D’UN TIERS (À L’EXCLUSION DES SOUS-TRAITANTS DE BRUME), DU CLIENT ; D’UN TIER FOURNISSEUR, OU D’UN MANQUEMENT DU CLIENT À SES OBLIGATIONS ; (E) INCIDENTS DE SÉCURITÉ LIÉS À L’UTILISATION D’INTERNET, NOTAMMENT EN CAS DE PERTE, ALTÉRATION, DESTRUCTION, DIVULGATION OU ACCÈS NON AUTORISÉ À DES DONNÉES OU INFORMATIONS DU CLIENT SUR OU À PARTIR DU RÉSEAU INTERNET ; (F) PERTE, DIVULGATION OU UTILISATION ILLICITE OU FRAUDULEUSE DE MOYENS D’AUTHENTIFICATION DES UTILISATEURS DU FAIT DU CLIENT OU DE TIERS ; (G) INADÉQUATION DES SERVICES AUX BESOINS DU CLIENT (NOTAMMENT EU ÉGARD À LA SENSIBILITÉ DES DONNÉES CONCERNÉES).</p>

      <p><strong>6.4. Responsabilité du Client.</strong> Le Client supporte intégralement les risques et périls associés à ses activités et est le seul responsable de l’utilisation des Services fournis par Brume ainsi que du respect des dispositions contractuelles, même lorsqu’ils sont utilisés par des tiers ou pour leur compte. Le Client est également tenu responsable (a) des Contenus créés dans le cadre des Services, (b) de la vérification préalable à l’utilisation et à la diffusion de ces Contenus, y compris lorsqu’ils sont exploités par des tiers ou pour leur compte, et (c) du respect des lois et réglementations en vigueur.</p>

      <p><strong>6.5. Garantie.</strong> Chacune des Parties garantit que ses activités sont conduites conformément à la réglementation en vigueur. Le Client garantit Brume contre toutes les conséquences découlant (a) de l’utilisation ou de l’exploitation des Contenus générés dans le cadre des Services, (b) de l’usage frauduleux ou non conforme aux lois et réglementations en vigueur des Services, (c) de l’utilisation des Services en violation des droits de tiers, ainsi que (d) de la perte ou de l’utilisation frauduleuse ou non-autorisée des moyens d’authentification des Utilisateurs. Le Client s’engage à intervenir dans toutes les réclamations, demandes et/ou actions de tiers concernant les Contenus et/ou les dispositions du Contrat, y compris les autorités administratives et judiciaires, et à indemniser Brume pour tous les préjudices en résultant (y compris condamnations, frais de défense raisonnables, etc.).</p>

      <p><strong>6.6. Tiers.</strong> En vertu du présent Contrat, Brume ne contracte aucun engagement envers des tiers, y compris les Utilisateurs, et aucune stipulation ne pourra être interprétée comme créant des tiers bénéficiaires du présent Contrat. En ce qui concerne les relations avec les Utilisateurs des Services, le Client en est le seul responsable et doit garantir Brume contre toutes réclamations, demandes et/ou actions de tiers portant sur les Services de Brume. Le Client s’engage à informer Brume par écrit dans les meilleurs délais, de toute réclamation, demande et/ou action de tiers impliquant les Services de Brume, en indiquant précisément l’objet de la demande et en fournissant toute information utile pour permettre à Brume de communiquer les éléments nécessaires en sa possession au Client.</p>

      <p><strong>6.7. Force Majeure.</strong> A l’égard d’une défaillance survenue, qu’elle soit de manière directe ou indirecte, en raison d’événements imprévisibles ayant les attributs de la force majeure définie par l’article 1218 du Code Civil, aucune Partie ne peut voir sa responsabilité engagée. En ce qui concerne la force majeure, les Parties conviennent qu’elle englobe notamment les conflits sociaux, y compris la grève des salariés des sous-traitants de l’une des Parties, les actes de guerre, les sabotages, les menaces de guerre, les actes de terrorisme, les incendies, les tremblements de terre, les épidémies, les inondations et explosions, ainsi que les interruptions de courant échappant au contrôle de la Partie concernée. Néanmoins, pour pouvoir invoquer cette clause, la Partie empêchée d’honorer ses obligations doit notifier sans délai et par écrit les circonstances et la durée probable de l’empêchement à l’autre Partie, tout en la tenant régulièrement informée de l’évolution de la situation. Si la défaillance persiste malgré les efforts déployés par la Partie défaillante au-delà d’une durée ininterrompue de trente (30) jours, l’autre Partie peut résilier de plein droit tout ou partie des Services concernés.</p>

      <h2 id="article-7"><strong>ARTICLE 7 : CONDITIONS FINANCIERES&nbsp;</strong></h2>

      <p><strong>7.1. Prix des Services.</strong> Les prix des Services facturés au Client sont ceux en vigueur au moment de la facturation, tels que publiés sur le Site Internet de Brume. Les prix sont également communiqués sur simple demande adressée au Support Brume. Sauf stipulation contraire, les prix sont en euros et hors taxes. En fonction du type de Services, Brume propose différents types de tarifs (prix forfaitaire mensuel, prix forfaitaire annuel, prix à l’usage, etc.) auxquels peuvent être associés, selon le cas, une durée d’engagement et/ou un mode de facturation spécifique.</p>

      <p><strong>7.2. Crédits.</strong> Les Crédits, sauf indication contraire au moment de la Souscription, doivent être utilisés par le Client dans un délai de douze mois après leur acquisition. À l’exception des dispositions mentionnées à l’Article “9.4. Modification du Contrat” et “7.5. Changement de prix,” ils ne sont pas remboursables.</p>

      <p><strong>7.3. Type de Crédits.</strong> Les différents types de Crédits, permettant l’utilisation des Services de Brume, sont détaillés sur le Site internet de Brume.</p>

      <p><strong>7.4. Balances de Crédits.</strong> Chaque Compte Client dispose d’une Balance de Crédits par type de Crédits, représentant le total des Crédits disponibles pour l’utilisation d’un type de Service sur la Plateforme. Cette Balance est affectée par l’achat de Crédits, et leur consommation lors de l’utilisation des Services concernés. La Balance de Crédits est mise à jour en temps réel pour refléter les Crédits restants après chaque opération.</p>

      <p><strong>7.5. Changement de prix.</strong> Brume se réserve le droit de modifier ses tarifs à tout moment. Les nouvelles tarifications entreront en vigueur immédiatement pour toute nouvelle Commande. En cas d’augmentation de prix, les Clients utilisant les Services en cours d’utilisation seront informés par courrier électronique avec un préavis de trente (30) jours calendaires. À compter de cette notification, le Client disposera d’un délai de trente (30) jours calendaires pour résilier sans frais les Services concernés, soit par courrier recommandé avec accusé de réception, soit via le formulaire prévu à cet effet dans son Interface de Gestion. Les Crédits non utilisés seront remboursés proportionnellement à leur valeur d’achat initiale, en tenant compte du nombre de crédits déjà consommés. Aucun remboursement ne sera effectué pour les crédits octroyés gratuitement. Le remboursement interviendra dans un délai maximum de trente (30) jours suivant la réception de la demande de résiliation. À défaut de résiliation, le Client sera réputé avoir accepté les nouveaux tarifs. La faculté de résiliation précitée n’est pas applicable en cas d’augmentation de prix résultant de circonstances imprévisibles au sens de l’article 1195 du Code civil. Dans ce cas, les dispositions dudit article s’appliquent.</p>

      <p><strong>7.6. Facturation.</strong> Les conditions de facturation des prix des Services sont définies sur le Site Internet de Brume. Avant de passer commande, le Client doit en prendre connaissance. Une fois chaque paiement effectué, une facture est envoyée par Brume au Client. Le Client consent expressément à la réception de la facture par voie électronique. La facture est soit mise à disposition du Client dans l’Interface de Gestion, soit communiquée par courrier électronique. Il incombe au Client de conserver une copie de la facture conformément à la réglementation applicable. Pendant une durée de douze (12) mois suivant leur date de mise à disposition, les factures restent disponibles dans l’Interface de Gestion du Client.</p>

      <p><strong>7.7. Paiement.</strong> Les factures sont payables à réception. Les montants facturés sont exigibles en totalité. Par conséquent, (a) en cas de non-utilisation, d’utilisation partielle, d’arrêt ou de suspension de l’utilisation des Services avant la fin de la période d’utilisation, le Client ne peut réclamer aucun remboursement. (b) En cas de paiement fractionné (mensuel, annuel ou autre), le Client demeure redevable de l’intégralité des sommes dues pour la période d’engagement indiquée lors de la Commande. Cela est sans préjudice pour le Client d’engager, dans les conditions stipulées à l’article « Responsabilité » ci-après, la responsabilité de Brume, si ladite situation découle d’un manquement de Brume à ses obligations contractuelles.</p>

      <p><strong>7.8. Défaut et retard de paiement.</strong>&nbsp; En cas de retard ou de défaut de paiement, y compris en cas de paiement partiel, le Client est redevable de pénalités de retard le jour suivant la date limite de règlement, avec un taux d’intérêt égal à trois fois celui de l’intérêt légal. De plus, tout retard ou défaut de paiement des sommes dues par le Client en exécution du Contrat, même partiel et persistant plus de quatre (4) jours calendaires après notification par courriel, entraîne de plein droit et sans mise en demeure ou notification supplémentaire : (a) l’exigibilité immédiate de toutes les sommes dues par le Client, et ce quel que soit le mode de règlement prévu, ainsi que (b) la suspension immédiate et sans préavis par Brume de tout ou partie des Services du Client (y compris ceux déjà réglés), le refus de toute nouvelle Commande ou renouvellement de Services, et la résiliation de plein droit, par courriel, du Contrat en tout ou partie. En cas de défaut ou de retard de paiement, les professionnels sont redevables d’une indemnité forfaitaire pour frais de recouvrement de quarante (40) euros, sans préjudice de la possibilité pour Brume de demander, sur justification, une indemnisation complémentaire lorsque les frais de recouvrement exposés sont supérieurs à ladite indemnité forfaitaire.</p>

      <p><strong>7.9. Contestation.</strong> Toute contestation relative à la nature des Services et à la facturation doit être signalée au Support Brume, via l’Interface de gestion du Client, dans un délai d’un (1) mois suivant l’émission de la facture. À défaut, et indépendamment du droit du Client de contester postérieurement la facturation, le Client est obligé de régler les factures impayées conformément aux modalités prévues par le Contrat. En cas de défaut de facturation, dans la limite des règles de prescription applicables, Brume est habilitée à régulariser lesdites factures.</p>

      <h2 id="article-8"><strong>ARTICLE 8 : DUREE, RENOUVELLEMENT ET RÉSILIATION DES SERVICES&nbsp;</strong></h2>

      <p><strong>8.1. Durée des Services.</strong> Le Contrat est conclu pour une durée indéterminée et reste en vigueur tant que le Client utilise des Services de Brume. L’engagement du Client à utiliser les Services commandés est déterminé par l’option tarifaire choisie lors de la Commande (la « <strong>Période d’engagement</strong> »). Si le paiement se fait par abonnement, au forfait (mensuel, annuel ou autre), le Client doit utiliser les Services pendant toute la période correspondante. En cas de suspension ou d’arrêt anticipé des Services, notamment, le Client est tenu de payer le forfait en totalité et ne peut prétendre à aucun remboursement à cet égard. Lorsque le paiement se fait à l’usage, les Services sont disponibles pour une durée indéterminée; le Client peut mettre fin aux Services à tout moment selon les modalités en vigueur.</p>

      <p><strong>8.2. Renouvellement des Services.</strong> Par défaut, certains Services incluent un renouvellement automatique. En cas de défaut de paiement ou de paiement irrégulier (notamment paiement incomplet, montant erroné, absence des références requises, ou réalisé par une procédure ou un moyen non approuvé par Brume), les demandes de renouvellement par paiement sont automatiquement rejetées. Brume se réserve le droit de mettre fin à un renouvellement, notamment en cas de disparition du Service avec un préavis raisonnable.</p>

      <p><strong>8.3. Résiliation pour manquement.</strong> Sans préjudice des autres cas de résiliation prévus au Contrat, les Services peuvent être résiliés par courrier recommandé avec accusé de réception si l’une des Parties manque à tout ou partie de ses obligations, notamment en cas de non-respect des conditions financières et/ou de l’article 4 « Conditions d’utilisation des Services » des Conditions Générales de Service, après que la Partie défaillante ait réceptionné une notification des manquements par courrier recommandé avec accusé de réception, et que celle-ci soit restée sans effet pendant plus de sept (7) jours calendaires. En cas d’utilisation illicite, malveillante ou frauduleuse des Services, ou d’utilisation en violation des droits d’un tiers, Brume peut, de plein droit et sans mise en demeure préalable, résilier les Services concernés ou le Contrat dans son intégralité par courriel. Nonobstant ce qui précède, le droit pour Brume de suspendre ou d’interrompre les Services, notamment en cas de non-respect des dispositions du Contrat, demeure dans les conditions prévues au Contrat. Les résiliations pour manquement n’affectent pas le droit de réclamer des dommages et intérêts à la Partie défaillante. Aucune réduction de prix ou exécution forcée en nature en vertu des articles 1217 et suivants du Code civil ne pourra être sollicitée par le Client en cas d’inexécution contractuelle de la part de Brume.</p>

      <h2 id="article-9"><strong>ARTICLE 9 : CONFIDENTIALITE&nbsp;</strong></h2>

      <p><strong>9.1. Engagements.</strong> Chacune des Parties, concernant les informations confidentielles de l’autre Partie dont elle est récipiendaire ou auxquelles elle a accès dans le cadre de l’exécution du présent Contrat, s’engage à : (a) les utiliser uniquement aux fins exclusives de l’exécution du Contrat, (b) préserver leur confidentialité avec le même degré de soin que s’il s’agissait de ses propres informations confidentielles, et (c) ne donner accès à ces informations qu’à ses collaborateurs et Sociétés Apparentées ayant besoin d’en connaître en raison de leur fonction, sous réserve que ces derniers soient préalablement informés de leur caractère confidentiel et qu’ils soient liés par un engagement de confidentialité au moins équivalent au présent engagement. Chacune des Parties est également autorisée à communiquer lesdites informations confidentielles à ses conseils professionnels régis par le secret professionnel (comme les avocats, experts-comptables ou commissaires aux comptes). Sans l’accord préalable et écrit de l’autre Partie, chacune des Parties s’interdit de divulguer les informations confidentielles à d’autres personnes que celles susmentionnées, et se porte fort du respect de la confidentialité par toutes les personnes auxquelles ces informations sont divulguées. Les conditions du Contrat et toute autre information échangée entre les Parties ou accessible dans le cadre de l’exécution du Contrat sont considérées comme confidentielles, quelle qu’en soit la forme et la nature (y compris secrets de fabrique,&nbsp; savoir-faire, informations financières et marketing, informations relatives à la sécurité et aux conditions d’utilisation des Services). Il n’est pas nécessaire que le caractère confidentiel soit mentionné sur le document ou support contenant l’information pour qu’elle soit considérée comme confidentielle, et cela n’a pas besoin d’être précisé au moment de la divulgation. L’obligation de confidentialité de chaque Partie s’étend sur la durée du Contrat et pendant une période de deux (2) ans après sa fin, quelle qu’en soit la cause.</p>

      <p><strong>9.2. Exceptions.</strong> Les engagements de confidentialité tels que définis ci-dessus ne s’appliquent pas aux informations pour lesquelles la Partie récipiendaire peut prouver (a) qu’elles étaient légitimement en sa possession sans obligation de confidentialité avant qu’elle y ait eu accès ou avant leur communication par l’autre Partie, (b) qu’elles se trouvent dans le domaine public autrement que par une violation de la confidentialité par la Partie récipiendaire (ou par les personnes dont elle porte la responsabilité), (c) qu’elles ont été transmises par un tiers de manière légitime avec une autorisation de divulgation, (d) qu’elles résultent de développements réalisés par la Partie récipiendaire et/ou ses collaborateurs indépendamment de l’exécution du Contrat, ou (e) que leur divulgation a été autorisée par l’autre Partie dans les conditions du Contrat. Nonobstant ce qui précède, chacune des Parties se réserve le droit de divulguer les informations reçues de l’autre Partie (a) dans la limite strictement nécessaire à la défense de ses droits, en précisant que dans ce cas, les informations confidentielles de l’autre Partie sont conservées aussi longtemps que nécessaire à l’administration de la preuve et ne peuvent être divulguées qu’à des personnes ayant besoin de les connaître dans le cadre de l’action ou de la procédure en cause (magistrats, conseils, etc.), lesquelles sont soumises au secret professionnel ou, à défaut, à un accord de confidentialité, et (b) à la demande d’une autorité administrative ou judiciaire compétente, en précisant que dans un tel cas, la divulgation sera strictement limitée à ce qui est requis par ladite autorité et que, sous réserve de toute disposition légale ou injonction contraire, la Partie récipiendaire informe l’autre Partie de cette demande.</p>

      <h2 id="article-10"><strong>ARTICLE 10 : DISPOSITIONS GENERALES&nbsp;</strong></h2>

      <p><strong>10.1. Divisibilité.</strong> La nullité de l’une des dispositions du Contrat conclu avec Brume en vertu notamment d’un règlement, d’une loi ou suite à une décision d’un tribunal ayant force de chose jugée, n’affectera pas la validité des autres stipulations contractuelles qui demeureront pleinement en vigueur. Dans cette hypothèse, les Parties devront, dans la mesure du possible, substituer à la clause annulée une disposition valable conforme à l’esprit et à l’objet des Conditions contractuelles.</p>

      <p><strong>10.2. Intitulés.</strong> Servant uniquement à faciliter les références, les intitulés des articles des conditions contractuelles n’ont ni signification particulière, ni valeur contractuelle par eux-mêmes.</p>

      <p><strong>10.3. Tolérance. </strong>Le fait que Brume tolère à un moment donné une violation par l’autre Partie d’une quelconque des obligations stipulées dans les présentes Conditions générales et/ou qu’elle ne se prévale pas immédiatement de l’une quelconque desdites Conditions ne pourra être interprété comme une renonciation par Brume à faire valoir ultérieurement l’une quelconque de ces Conditions.</p>

      <p><strong>10.4. Modification du Contrat.</strong> Le Contrat est composé des Conditions Générales de Service, lesquelles constituent l’intégralité de l’accord entre le Client et Brume, à l’exclusion de tout autre document, accord ou discussion antérieurs. Brume se réserve le droit de modifier à tout moment et de plein droit ces Conditions Générales de Service. Ces modifications sont immédiatement applicables à toutes nouvelles Commandes. Quant aux Services en cours d’utilisation, le Client est informé par e-mail ou via son Interface de gestion de toute modification en vigueur des Conditions Générales de Service. Les modifications des Conditions Générales de Service prennent effet seulement trente (30) jours calendaires après la notification correspondante. Néanmoins, les mises en conformité légale ou réglementaire peuvent être appliquées immédiatement puisqu’elles échappent au contrôle de Brume. En cas de nouvelles Conditions Générales de Service défavorables au Client, ce dernier a la possibilité de résilier les Services concernés par courrier recommandé avec accusé de réception ou via le formulaire prévu à cet effet dans son Interface de Gestion, dans un délai maximum de trente (30) jours calendaires à compter de la date d’effet des nouvelles Conditions Générales de Service. Les Crédits restants seront remboursés au prorata de leur valeur initiale d’achat en tenant compte du nombre de crédits utilisés. Aucun remboursement ne sera effectué pour les crédits offerts gratuitement. Le remboursement sera effectué dans un délai maximum de trente (30) jours suivant la réception de la demande de résiliation.</p>

      <p><strong>10.5. Indépendance.</strong> Les Parties conviennent que rien dans le Contrat ne peut être interprété comme étant constitutif d’une société créée de fait, d’un mandat, d’une joint-venture ou d’une association, d’une entreprise commune, d’un groupement ou d’une société en participation ou d’une quelconque autre forme de collaboration. Chaque Partie reste autonome, gère seule ses affaires, est responsable de tous ses actes et assume exclusivement l’ensemble des risques associés à son activité.</p>

      <p><strong>10.6. Cession de Contrat.</strong> Sauf accord préalable écrit de l’autre Partie, aucune des Parties n’est autorisée à céder, même partiellement, le présent Contrat. Cela étant, par dérogation, chacune des Parties peut librement céder en tout ou partie le présent Contrat à ses Sociétés Apparentées, moyennant notification écrite dans les plus brefs délais à l’autre Partie, et en se portant fort du respect par la ou les Sociétés Apparentées cessionnaires du Contrat. Les opérations suivantes, autorisées et n’entrant pas dans le champ d’application du présent article, incluent : (a) changements de participation, actionnariat et contrôle de l’une ou l’autre des Parties, ainsi que (b) les fusions, absorptions, cessions d’activité, cessions de fonds de commerce, et autres opérations entraînant un transfert de patrimoine de l’une ou l’autre des Parties. En cas de réalisation d’une des opérations des points (a) et (b) ci-dessus, elle en informe l’autre Partie. Si cette opération bénéficie à un concurrent direct ou à une société en contentieux avec l’autre Partie, cette dernière peut résilier le Contrat de plein droit et sans indemnité.</p>

      <p><strong>10.7. Communications.</strong> Concernant l’échange d’informations par courrier électronique, la date et l’heure du serveur de Brume seront considérées comme faisant foi entre les Parties. Ces informations seront conservées par Brume pendant toute la durée des relations contractuelles, ainsi que pendant les trois (3) années suivant leur terme. Sous réserve des autres destinataires et modes de communication spécifiés au Contrat, toutes les notifications, mises en demeure et autres communications prévues au Contrat seront réputées valablement délivrées si elles sont adressées :</p>

      <ul>
        <li>A Brume : Par lettre recommandée avec accusé de réception à l’adresse suivante : LAHAYE – 14 rue de la Brasserie – 44100 NANTES</li>
        <li>Au Client : Par lettre recommandée avec accusé de réception à l’adresse postale associée à son Compte Client ou par courriel.&nbsp;</li>
      </ul>

      <p><strong>10.8 Publicité et promotion.</strong> Sauf avis contraire du Client transmis via son Interface de Gestion, Brume est autorisée à se réclamer de la relation commerciale existante entre le Client et Brume dans le cadre habituel de ses activités commerciales auprès de ses prospects et clients. Toute autre mention par Brume du Client, ainsi que toute utilisation de ses signes distinctifs (marques, logos, etc.), notamment dans le cadre de manifestations publiques, publicités, publications spécialisées sur les marchés professionnels, colloques, ou sur ses documents commerciaux, plaquettes ou Site Internet de Brume, est soumise à l’approbation préalable du Client.</p>

      <p><strong>10.9 Convention de preuve.</strong> Il est expressément convenu que les données du système d’information de Brume ou de ses sous-traitants, telles que les logs de connexion, les récapitulatifs de commandes et de paiement, les relevés de consommation, les comptes-rendus de gestion des Incidents ou d’autres, sont pleinement opposables au Client et recevables, y compris dans le cadre de procédures contentieuses.</p>

      <p><strong>10.10 Calcul des délais. </strong>En dépit des dispositions des articles 640 et suivants du Code de procédure civile, et sous réserve de stipulations contraires dans le présent Contrat, les délais sont comptabilisés en jours calendaires, prenant effet à partir du jour suivant l’événement déclencheur.</p>

      <p><strong>10.11 Survivance.</strong> La résiliation anticipée du Contrat ou l’arrivée du terme n’affectera en rien la validité des obligations et droits prévus aux articles « Propriété Intellectuelle », « Communication », « Responsabilité », « Compétence juridictionnelle et loi applicable », « Confidentialité » du Contrat, qui, par leur nature ou en raison des stipulations spécifiques, se prolongeront au-delà de cette résiliation ou du terme, aussi bien pour les Parties que pour leurs ayants-droits, et ce jusqu’à leur échéance respective.</p>

      <h2 id="article-11"><strong>ARTICLE 11 : COMPÉTENCE JURIDICTIONNELLE ET LOI APPLICABLE&nbsp;</strong></h2>

      <p><strong>11.1. Compétence Juridictionnelle.</strong> En cas de litige avec un client ne relevant pas de la notion de Consommateur définie par le Code de la consommation, le Tribunal de Commerce de Nantes (France) se voit expressément attribuer la compétence, y compris pour les mesures d’urgence, conservatoires sur requête ou en référé, et ce, malgré pluralité de défendeurs ou appel en garantie.</p>

      <p><strong>11.2. Loi applicable.</strong> Ce contrat est soumis à la législation française. Ainsi, cela vaut tant pour les règles de forme que les règles de fond, à l’exception, d’une part, des dispositions législatives françaises contraires au présent Contrat et, d’autre part, des règles de conflit stipulées par la loi française.</p>
    </div>
  );
};

export { CGV };
